MODULE PS7PARA
    IMPLICIT NONE
    REAL(KIND=8), PARAMETER:: BETA=0.96, SIGMA=1, ALPHA=0.33, DELTA=0.06
    INTEGER, PARAMETER:: NK=40, NKBAR=10
    INTEGER:: I
    REAL(KIND=8), PARAMETER:: K_MIN=0.01, K_MAX=10., STEP=(10.-0.01)/40.
    REAL(KIND=8), DIMENSION(NK), PARAMETER:: K_GRID=(/(I*STEP, I=1, NK)/) +K_MIN - STEP
    REAL(KIND=8), PARAMETER:: KBAR_MIN=0.01, KBAR_MAX=10., BAR_STEP=4./9.
    REAL(KIND=8), DIMENSION(NK), PARAMETER:: KBAR_GRID=(/(I*BAR_STEP, I=1, NKBAR)/) +KBAR_MIN - BAR_STEP
    REAL(KIND=8):: A0=0.05, A1=0.9
END MODULE

MODULE PS7RES
    PS7PARA
    IMPLICIT NONE
    REAL(KIND=8), DIMENSION(NKBAR):: INTEREST, WAGE
    REAL(KIND=8), DIMENSION(NK):: K2BAR

    CONTAINS
        SUBROUTINE INIT_RW()
            DO I=1, NKBAR
                INTEREST(I)= ALPHA*(KBAR_GRID(I)**(ALPHA-1))-DELTA
                WAGE(I)= (1-ALPHA)*(KBAR_GRID(I)**ALPHA)
                K2BAR(I) = EXP(A0+A1*LOG(KBAR_GRID(I)))
            ENDDO
        END SUBROUTINE
END MODULE

PROGRAM PS7
    USE PS7PARA
    USE PS7RES
    IMPLICIT NONE
    REAL(KIND=8), DIMENSION(NKBAR):: INTEREST, WAGE
    INTEGER:: KBIDX

    DO KBIDX=1, NKBAR
        
    ENDDO

END PROGRAM PS7

SUBROUTINE LIN_SPLINE()
    USE PS7PARA
    IMPLICIT NONE

    


END SUBROUTINE

