MODULE PS8PARA
    IMPLICIT NONE
    REAL(KIND=8):: BETA=0.99, ALPHA=0.36, DELTA=0.025
    REAL(KIND=8), DIMENSION(2), PARAMETER:: PROD_SHOCKS=(/1.01, 0.99/), EMP_STATES=(/1.,0./)
    REAL(KIND=8), PARAMETER:: K_MIN=0.01, K_MAX=15.0 ! DEFINE SMALL K GRIDS
    REAL(KIND=8), PARAMETER:: AGG_K_MIN=0.01, AGG_K_MAX=15.0
    INTEGER
    END MODULE

MODULE PS8RES
    IMPLICIT NONE
END MODULE

PROGRAM PS8
    IMPLICIT NONE
END PROGRAM

SUBROUTINE
    IMPLICIT NONE
END SUBROUTINE
